In [2]:
import torch

In [24]:
# Scalar

scalar = torch.tensor(10)
scalar, scalar.dtype, scalar.device, scalar.ndim, scalar.shape, scalar.item()

(tensor(10), torch.int64, device(type='cpu'), 0, torch.Size([]), 10)

In [45]:
# Vector

vector = torch.tensor([7, 8]) 
vector, vector.shape, vector.ndim, vector.tolist()

(tensor([7, 8]), torch.Size([2]), 1, [7, 8])

In [56]:
# Matrix

matrix = torch.tensor([[1,2], 
                       [3, 4]])
matrix, matrix.dtype, matrix.shape, matrix.ndim

(tensor([[1, 2],
         [3, 4]]),
 torch.int64,
 torch.Size([2, 2]),
 2)

In [60]:
# Tensor

tensor = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6], 
                        [7, 8, 9]]])

tensor.size(), tensor.shape, tensor.ndim

(torch.Size([1, 3, 3]), torch.Size([1, 3, 3]), 3)

In [87]:
random_tensor = torch.rand((3, 4))
print(random_tensor)
print( random_tensor.dtype)

zeros = torch.zeros(size=(5, 4))
print(zeros)
print(zeros.shape)

ones = torch.ones(size=(2, 6))
print(ones)
print(ones.shape)


tensor([[0.6179, 0.3610, 0.8433, 0.2524],
        [0.0232, 0.8082, 0.5173, 0.2543],
        [0.3276, 0.6645, 0.9315, 0.7405]])
torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([5, 4])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([2, 6])


In [95]:
zero_to_ten = torch.arange(0, 10, 1)

print(zero_to_ten)

ten_zeros = torch.zeros_like(zero_to_ten)
ten_ones = torch.ones_like(zero_to_ten)
 
print(ten_zeros)
print(ten_ones)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [103]:
# Tensor dtype

float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [110]:
# Operation with scalar

ts = torch.tensor([1, 2, 3])


print('Addition', ts + 10)
print('Multiply', ts * 10)
print('Subtraction', ts - 10)

print('Original', ts)

Addition tensor([11, 12, 13])
Multiply tensor([10, 20, 30])
Subtraction tensor([-9, -8, -7])
Original tensor([1, 2, 3])


In [127]:
# Operation with tensor

ts1 = torch.rand(3)
 
print(ts1,  ts1 * ts1, torch.multiply(ts1, ts1))

tsa = torch.rand(size=(2, 3))
tsb = torch.rand(size=(3, 4))

print(torch.mm(tsa, tsb))

tensor([0.5537, 0.8983, 0.7046]) tensor([0.3065, 0.8070, 0.4964]) tensor([0.3065, 0.8070, 0.4964])
tensor([[0.1604, 0.4846, 0.2019, 0.2788],
        [0.8856, 1.1308, 1.0947, 0.5951]])


In [131]:
# Manual seed

torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

x = torch.rand(5, 2)
output = linear(x)
print(f"Input: {x}\n")
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input: tensor([[0.2666, 0.6274],
        [0.2696, 0.4414],
        [0.2969, 0.8317],
        [0.1053, 0.2695],
        [0.3588, 0.1994]])

Input shape: torch.Size([5, 2])

Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971],
        [ 0.7375,  0.2534,  0.3631, -0.0242,  0.4709,  0.2049],
        [ 0.8334,  0.1658,  0.3138, -0.1406,  0.6653,  0.3514]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([5, 6])


In [136]:
ts = torch.arange(0, 100, 10, dtype=torch.float16)

ts.min(), ts.max(), ts.mean(), ts.sum(), ts.argmin(), ts.argmax()

(tensor(0., dtype=torch.float16),
 tensor(90., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(450., dtype=torch.float16),
 tensor(0),
 tensor(9))

In [156]:
# Transform

x = torch.arange(1, 8)
print('original', x, x.shape)

x_reshaped = x.reshape(1, 7)
print('reshaping', x_reshaped, x_reshaped.shape)

x_view = x.view(1, 7)
print('viewing', x_view, x_view.shape)

x_view[:, 5] = 5

print('viewing', x, x_view, x == x_view)

x_stacked = torch.stack([x, x, x], dim=1)

print(x_stacked)

print('squeeze', x_reshaped.unsqueeze(dim=0))

original tensor([1, 2, 3, 4, 5, 6, 7]) torch.Size([7])
reshaping tensor([[1, 2, 3, 4, 5, 6, 7]]) torch.Size([1, 7])
viewing tensor([[1, 2, 3, 4, 5, 6, 7]]) torch.Size([1, 7])
viewing tensor([1, 2, 3, 4, 5, 5, 7]) tensor([[1, 2, 3, 4, 5, 5, 7]]) tensor([[True, True, True, True, True, True, True]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [5, 5, 5],
        [7, 7, 7]])
squeeze tensor([[[1, 2, 3, 4, 5, 5, 7]]])


In [161]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(1, 2, 0) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


In [177]:
z = torch.arange(1, 10).reshape(1, 3, 3)
print (z, z.shape)

zz = z.squeeze(dim=0)
print(zz, zz.shape)

print(z[0,:], zz[0, :])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) tensor([1, 2, 3])


In [182]:
# Torch and NumPy

import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array + 1, tensor + 2, array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [183]:
ts = torch.ones(7)
np_tensor = ts.numpy()

ts, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [184]:
!nvidia-smi


'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
